# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:27
from __future__ import unicode_literals

from django.db import migrations
import touchtechnology.common.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=touchtechnology.common.db.models.ManyToManyField(blank=True, to='news.Category', verbose_name='Categories'),
        ),
    ]
