# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import touchtechnology.common.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_normalise_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_class',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(choices=[(b'copy', 'Copy')]), null=True, size=None),
        ),
        migrations.AddField(
            model_name='article',
            name='content_copy',
            field=django.contrib.postgres.fields.ArrayField(base_field=touchtechnology.common.db.models.HTMLField(blank=True), null=True, size=None),
        ),
    ]
