# Generated by Django 2.2.8 on 2019-12-11 19:38

import touchtechnology.common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_auto_20191122_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(
                blank=True, verbose_name="Copy"
            ),
        ),
    ]
