# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:31
from __future__ import unicode_literals

from django.db import migrations


def populate_content(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    for article in Article.objects.prefetch_related('content'):
        article.content_copy = [a.copy for a in article.content.all()]
        article.content_class = [a.label for a in article.content.all()]
        article.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_content_arrayfields'),
    ]

    operations = [
        migrations.RunPython(populate_content, noop)
    ]
