# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_content_arrayfields_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
    ]
