# Generated by Django 2.2.8 on 2019-12-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_article_copy_field_data"),
    ]

    operations = [
        migrations.DeleteModel(name="ArticleContent",),
    ]
