changelog:
  categories:
    - title: ":loudspeaker: Updates"
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - dependencies
          - maintenance
          - performance
          - removed
    - title: ":rocket: Performance"
      labels:
        - performance
    - title: ":lady_beetle: Bug fixes"
      labels:
        - bug
    - title: ":broom: Maintenance"
      labels:
        - maintenance
    - title: ":scissors: Removals"
      labels:
        - removed
    - title: ":wrench: Dependencies"
      labels:
        - dependencies
