repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: setup.cfg
      - id: flake8
        exclude: migrations/\d+_.+\.py$
      - id: pretty-format-json
  - repo: git://github.com/pre-commit/mirrors-isort
    sha: v4.3.4
    hooks:
      - id: isort
