# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 20:41
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import touchtechnology.common.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0028_drop_matchvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='primary',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, help_text='Appears on the front-end with other club information.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competition.Person', verbose_name='Primary contact'),
        ),
        migrations.AlterField(
            model_name='clubassociation',
            name='club',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='competition.Club'),
        ),
        migrations.AlterField(
            model_name='clubassociation',
            name='person',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Person'),
        ),
        migrations.AlterField(
            model_name='clubrole',
            name='competition',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_roles', to='competition.Competition'),
        ),
        migrations.AlterField(
            model_name='division',
            name='rank_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.RankDivision'),
        ),
        migrations.AlterField(
            model_name='division',
            name='season',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='competition.Season'),
        ),
        migrations.AlterField(
            model_name='divisionexclusiondate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ground',
            name='venue',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grounds', to='competition.Venue'),
        ),
        migrations.AlterField(
            model_name='ladderentry',
            name='opponent',
            field=touchtechnology.common.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='laddersummary',
            name='team',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ladder_summary', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_eval_related',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competition.Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_undecided',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='competition.UndecidedTeam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='forfeit_winner',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_eval_related',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competition.Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_undecided',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='competition.UndecidedTeam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=touchtechnology.common.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competition.Stage'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage_group',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competition.StageGroup', verbose_name='Pool'),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='club',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='competition.Club'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='season',
            name='competition',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='competition.Competition'),
        ),
        migrations.AlterField(
            model_name='season',
            name='mvp_results_public',
            field=models.DateTimeField(blank=True, help_text='The time when the results of the MVP voting will be made public on the website. Leave blank to show at all times.', null=True, verbose_name='MVP public at'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonassociation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='competition.Club'),
        ),
        migrations.AlterField(
            model_name='seasonassociation',
            name='person',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Person'),
        ),
        migrations.AlterField(
            model_name='seasonassociation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='competition.Season'),
        ),
        migrations.AlterField(
            model_name='seasonexclusiondate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seasonmatchtime',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Until'),
        ),
        migrations.AlterField(
            model_name='seasonmatchtime',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seasonmatchtime',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='simplescorematchstatistic',
            name='match',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statistics', to='competition.Match'),
        ),
        migrations.AlterField(
            model_name='simplescorematchstatistic',
            name='player',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statistics', to='competition.Person'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='division',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='competition.Division'),
        ),
        migrations.AlterField(
            model_name='stagegroup',
            name='stage',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='competition.Stage'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='competition.Division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.RankDivision'),
        ),
        migrations.AlterField(
            model_name='team',
            name='timeslots_after',
            field=models.TimeField(blank=True, help_text='Specify the earliest time that this team can play. Leave blank for no preference.', null=True, verbose_name='Start after'),
        ),
        migrations.AlterField(
            model_name='team',
            name='timeslots_before',
            field=models.TimeField(blank=True, help_text='Specify the latest time that this team can play. Leave blank for no preference.', null=True, verbose_name='Start before'),
        ),
        migrations.AlterField(
            model_name='teamassociation',
            name='person',
            field=touchtechnology.common.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.Person'),
        ),
        migrations.AlterField(
            model_name='teamassociation',
            name='team',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='competition',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_roles', to='competition.Competition'),
        ),
        migrations.AlterField(
            model_name='undecidedteam',
            name='stage',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='undecided_teams', to='competition.Stage'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='season',
            field=touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='competition.Season'),
        ),
    ]
