# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 21:22
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import touchtechnology.common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0029_alter_fields_to_match_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('reason', models.CharField(db_index=True, max_length=20)),
                ('sanction', models.CharField(db_index=True, max_length=20)),
                ('details', touchtechnology.common.db.models.HTMLField(blank=True)),
                ('cited_by', touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citings', to='competition.Person')),
                ('match', touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.Match')),
                ('subject', touchtechnology.common.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='competition.Person')),
                ('team', touchtechnology.common.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.Team')),
            ],
            options={
                'ordering': ('person__last_name', 'person__first_name'),
            },
        ),
    ]
