# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 09:13
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import django.utils.timezone
import tournamentcontrol.competition.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competition", "0032_resave_all_matches"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ("datetime",)},
            bases=(tournamentcontrol.competition.models.AdminUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MatchScoreEvent",
            fields=[
                (
                    "matchevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="competition.MatchEvent",
                    ),
                ),
                ("points", models.PositiveSmallIntegerField()),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="competition.TeamAssociation",
                    ),
                ),
            ],
            bases=("competition.matchevent",),
        ),
        migrations.CreateModel(
            name="MatchTimeEvent",
            fields=[
                (
                    "matchevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="competition.MatchEvent",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (b"COMMENCE", "Commenced"),
                            (b"BREAK", "Scheduled Break"),
                            (b"CONCLUDE", "Concluded"),
                            (b"OVERTIME", "Overtime"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
            ],
            bases=("competition.matchevent",),
        ),
        migrations.AddField(
            model_name="matchevent",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="competition.Match",
            ),
        ),
        migrations.AddField(
            model_name="matchevent",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
