# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("competition", "0032_resave_all_matches")]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": (
                    "-division__season__start_date",
                    "division__order",
                    "stage_group__order",
                    "order",
                )
            },
        )
    ]
