# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 09:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("competition", "0033_add_match_event_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchevent",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_competition.matchevent_set+",
                to="contenttypes.ContentType",
            ),
        )
    ]
