# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 21:31
from __future__ import unicode_literals

import touchtechnology.common.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("competition", "0033_matchscoresheet")]

    operations = [
        migrations.AddField(
            model_name="division",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="place",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="rankdivision",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="season",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="stage",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="stagegroup",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="copy",
            field=touchtechnology.common.db.models.HTMLField(blank=True),
        ),
    ]
