# Generated by Django 2.2.10 on 2020-02-27 20:35

import uuid

import django.db.models.deletion
import touchtechnology.common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0036_auto_20191122_1340"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("TOSS", "Coin Toss"),
                            ("TIME", "Timing Event"),
                            ("SCORE", "Scoring Event"),
                            ("DISCIPLINE", "Discipline Event"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("details", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "match",
                    touchtechnology.common.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline",
                        to="competition.Match",
                        to_field="uuid",
                    ),
                ),
                (
                    "team",
                    touchtechnology.common.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline",
                        to="competition.Team",
                    ),
                ),
            ],
        ),
    ]
