# Generated by Django 3.2.13 on 2022-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0036_auto_20191122_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="evaluated",
            field=models.BooleanField(null=True),
        ),
    ]
