# Generated by Django 3.2.13 on 2022-06-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0037_match_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEvent",
            fields=[
                (
                    "matchevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="competition.matchevent",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("START", "Started"),
                            ("RESUME", "Resume"),
                            ("QTR", "Quarter break"),
                            ("HALF", "Half-time break"),
                            ("PERIOD", "Period break"),
                            ("BREAK", "Break"),
                            ("FINISH", "Completed"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("competition.matchevent",),
        ),
    ]
