# Generated by Django 3.2.13 on 2022-07-24 02:57

from django.db import migrations
import touchtechnology.common.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0038_match_live_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="live_stream",
            field=touchtechnology.common.db.models.BooleanField(default=False),
        ),
    ]
