# Generated by Django 3.2.13 on 2022-07-30 10:22

from django.db import migrations

import touchtechnology.common.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0040_season_live_stream_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="ground",
            name="live_stream",
            field=touchtechnology.common.db.models.BooleanField(default=False),
        ),
    ]
