# Generated by Django 3.2.13 on 2022-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0042_ground_external_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ground",
            name="external_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
    ]
