# Generated by Django 3.2.19 on 2023-07-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0047_season_live_stream_oauth2"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="live_stream_thumbnail",
            field=models.URLField(null=True),
        ),
    ]
