# Generated by Django for MatchEvent model

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import touchtechnology.common.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0050_alter_place_timezone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("match_start", "Match Start"),
                            ("score_home", "Home Score"),
                            ("score_away", "Away Score"),
                            ("dismissal", "Dismissal"),
                            ("substitution", "Substitution"),
                            ("correction", "Correction"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order of events within the match",
                        verbose_name="Sequence",
                    ),
                ),
                (
                    "home_score_delta",
                    models.SmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Home Score Delta",
                    ),
                ),
                (
                    "away_score_delta",
                    models.SmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Away Score Delta",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "is_reversed",
                    touchtechnology.common.db.models.BooleanField(
                        default=False,
                        help_text="Indicates this event has been reversed/corrected",
                        verbose_name="Is Reversed",
                    ),
                ),
                (
                    "match",
                    touchtechnology.common.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="competition.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "player",
                    touchtechnology.common.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competition.person",
                        verbose_name="Player",
                    ),
                ),
                (
                    "reversed_by",
                    touchtechnology.common.db.models.ForeignKey(
                        blank=True,
                        help_text="The correction event that reversed this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competition.matchevent",
                        verbose_name="Reversed By",
                    ),
                ),
                (
                    "team_association",
                    touchtechnology.common.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competition.teamassociation",
                        verbose_name="Team Association",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Event",
                "verbose_name_plural": "Timeline",
                "ordering": ["match", "sequence"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="matchevent",
            unique_together={("match", "sequence")},
        ),
        migrations.AddIndex(
            model_name="matchevent",
            index=models.Index(
                fields=["match", "sequence"],
                name="competition_match_match_id_sequence_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchevent",
            index=models.Index(
                fields=["timestamp"], name="competition_match_timestamp_idx"
            ),
        ),
    ]
