# Generated by Django 5.2.1 on 2025-05-24 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0050_alter_place_timezone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEventType",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period", models.PositiveSmallIntegerField(default=1)),
                ("offset", models.DurationField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="competition.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline",
                        to="competition.person",
                    ),
                ),
                (
                    "related_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_related",
                        to="competition.person",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competition.team",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competition.matcheventtype",
                    ),
                ),
            ],
            options={
                "ordering": ("period", "offset", "pk"),
                "indexes": [
                    models.Index(
                        fields=["match", "period", "offset"],
                        name="competition_match_i_b513d9_idx",
                    ),
                    models.Index(
                        fields=["type"], name="competition_type_id_8200d0_idx"
                    ),
                ],
            },
        ),
    ]
