# Generated by Django 5.2.6 on 2025-12-20
# Migration to remove ranking-related tables and fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0055_remove_ranking_fkey_constraints"),
    ]

    operations = [
        # Remove ranking-related fields from existing tables
        
        # Remove rank_importance fields
        migrations.RemoveField(
            model_name="competition",
            name="rank_importance",
        ),
        migrations.RemoveField(
            model_name="season",
            name="rank_importance",
        ),
        migrations.RemoveField(
            model_name="division",
            name="rank_importance",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="rank_importance",
        ),
        migrations.RemoveField(
            model_name="stagegroup",
            name="rank_importance",
        ),
        migrations.RemoveField(
            model_name="match",
            name="rank_importance",
        ),
        
        # Remove rank_division fields
        migrations.RemoveField(
            model_name="division",
            name="rank_division",
        ),
        migrations.RemoveField(
            model_name="team",
            name="rank_division",
        ),
        
        # Drop ranking-related tables
        # Note: Foreign key constraints were already removed in migration 0055
        migrations.DeleteModel(
            name="RankPoints",
        ),
        migrations.DeleteModel(
            name="RankTeam",
        ),
        migrations.DeleteModel(
            name="RankDivision",
        ),
    ]