# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitemapnode_populate_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapnode',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitemapnode',
            name='restrict_to_groups',
            field=models.ManyToManyField(blank=True, help_text='If you select one or more of these groups your visitors will need to be logged in and a member of an appropriate group to view this part of the site.', to='auth.Group', verbose_name='Restrict to Groups'),
        ),
    ]
