# Generated by Django 5.2.3 on 2025-06-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0002_base_templates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basetemplate",
            options={"verbose_name": "Template", "verbose_name_plural": "Templates"},
        ),
        migrations.AlterModelOptions(
            name="seasontemplate",
            options={
                "verbose_name": "Season template",
                "verbose_name_plural": "Season templates",
            },
        ),
    ]
