# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_placeholderkeywordargument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
