# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-22 23:46
from __future__ import unicode_literals

import touchtechnology.common.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_model_definition_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='safe',
            field=touchtechnology.common.db.models.BooleanField(default=True),
        ),
    ]
