from constance import config

__all__ = (
    "APP_ROUTING",
    "CURRENCY_ABBREVIATION",
    "CURRENCY_SYMBOL",
    "PAGINATE_BY",
    "SITEMAP_CACHE_DURATION",
    "SITEMAP_EDIT_PARENT",
    "SITEMAP_HTTPS_OPTION",
    "SITEMAP_ROOT",
    "STORAGE_FOLDER",
    "STORAGE_URL",
)


APP_ROUTING = config.TOUCHTECHNOLOGY_APP_ROUTING
CURRENCY_ABBREVIATION = config.TOUCHTECHNOLOGY_CURRENCY_ABBREVIATION
CURRENCY_SYMBOL = config.TOUCHTECHNOLOGY_CURRENCY_SYMBOL
PAGINATE_BY = config.TOUCHTECHNOLOGY_PAGINATE_BY
PROFILE_FORM_CLASS = config.TOUCHTECHNOLOGY_PROFILE_FORM_CLASS
SITEMAP_CACHE_DURATION = config.TOUCHTECHNOLOGY_SITEMAP_CACHE_DURATION
SITEMAP_EDIT_PARENT = config.TOUCHTECHNOLOGY_SITEMAP_EDIT_PARENT
SITEMAP_HTTPS_OPTION = config.TOUCHTECHNOLOGY_SITEMAP_HTTPS_OPTION
SITEMAP_ROOT = config.TOUCHTECHNOLOGY_SITEMAP_ROOT
STORAGE_FOLDER = config.TOUCHTECHNOLOGY_STORAGE_FOLDER
STORAGE_URL = config.TOUCHTECHNOLOGY_STORAGE_URL
