"""
touchtechnology.common.translate

Common strings that we want translated because they could forseeably be added
in a database field that we want to translate.
"""

from django.utils.translation import ugettext_lazy as _


_("Argentina")
_("Australia")
_("Austria")
_("Belgium")
_("Bulgaria")
_("Canada")
_("Catalonia")
_("Chile")
_("China")
_("Chinese Taipei")
_("Cook Islands")
_("Czech Republic")
_("Egypt")
_("England")
_("Fiji")
_("France")
_("Germany")
_("Great Britain")
_("Guernsey")
_("Hong Kong")
_("Hungary")
_("India")
_("Iran")
_("Ireland")
_("Italy")
_("Japan")
_("Jersey")
_("Kenya")
_("Kiribati")
_("Lebanon")
_("Luxembourg")
_("Malaysia")
_("Mauritius")
_("Monaco")
_("Netherlands")
_("New Zealand")
_("Niue")
_("Norfolk Island")
_("Pakistan")
_("Papua New Guinea")
_("Philippines")
_("Portugal")
_("Qatar")
_("Samoa")
_("Scotland")
_("Singapore")
_("Solomon Islands")
_("South Africa")
_("Spain")
_("Sri Lanka")
_("Sweden")
_("Switzerland")
_("Thailand")
_("Tokelau")
_("Tonga")
_("Trinidad & Tobago")
_("Turkey")
_("Tuvalu")
_("United Arab Emirates")
_("United Kingdom of Great Britain and Northern Ireland")
_("United Kingdom")
_("United States of America")
_("United States")
_("Wales")
