from constance import config

__all__ = (
    "DETAIL_IMAGE_KWARGS",
    "DETAIL_IMAGE_PROCESSORS",
    "PAGINATE_BY",
    "THUMBNAIL_IMAGE_KWARGS",
    "THUMBNAIL_IMAGE_PROCESSORS",
)

DETAIL_IMAGE_KWARGS = config.TOUCHTECHNOLOGY_NEWS_DETAIL_IMAGE_KWARGS
DETAIL_IMAGE_PROCESSORS = config.TOUCHTECHNOLOGY_NEWS_DETAIL_IMAGE_PROCESSORS
PAGINATE_BY = config.TOUCHTECHNOLOGY_NEWS_PAGINATE_BY
THUMBNAIL_IMAGE_KWARGS = config.TOUCHTECHNOLOGY_NEWS_THUMBNAIL_IMAGE_KWARGS
THUMBNAIL_IMAGE_PROCESSORS = config.TOUCHTECHNOLOGY_NEWS_THUMBNAIL_IMAGE_PROCESSORS
